name: power  # 更改环境名称
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # 推荐版本
  - pip=21.3
  - numpy=1.21
  - pandas=1.3
  - matplotlib=3.5
  - scikit-learn=1.0
  - pytorch=1.12  # 稳定版本
  - cpuonly  # 移除此行可支持GPU版本（需要CUDA支持）
  - pip:
    - tqdm>=4.62.3
